src/test/java/de/qabel/core/http/StorageHTTPTest.java

Depends on and MUST NOT be merged before Qabel/qabel-storage#14
After the storage server being patched, the ignore annotations in the storage http tests are no longer necessary.
Furthermore, this enables proper tests of unknown QSV handling by using unkown, yet syntactically valid UUIDs.

Enable all storage http tests

---

src/main/java/de/qabel/core/crypto/QblPrimaryKeyPair.java
src/test/java/de/qabel/core/crypto/QblPrimaryPublicKeyInconsistencyTest.java

The two lists for signing and encryption sub-public keys are not updated by the QblPrimaryKeyPair constructor.

Fixed inconsistency in QblPrimaryPublicKey

---

src/test/java/de/qabel/core/http/DropHTTPTest.java

Solves current test failure of test postMessageTooBig.
Cherry picked from #258 to be faster reviewable ;-)
Not needed if #258 got merged first.

Hotfix: Increased size of too-big-drop-message

---

.travis.yml

Removes the checkout of the protocol_update branch, because the master branch is up-to-date.

Remove checkout of a specific qabel-storage branch

---

build.gradle
src/main/java/de/qabel/core/crypto/AbstractBinaryDropMessage.java
src/main/java/de/qabel/core/crypto/BinaryDropMessageV0.java
src/main/java/de/qabel/core/crypto/CryptoUtils.java
src/main/java/de/qabel/core/drop/DropController.java
src/main/java/de/qabel/core/exceptions/QblVersionMismatchException.java
src/test/java/de/qabel/core/MultiPartCryptoTest.java
src/test/java/de/qabel/core/drop/DropControllerTest.java
src/test/java/de/qabel/core/http/DropHTTPTest.java

This implements
* a basic binary drop message handling API
* handling of binary drop message in the current version (0)
EDIT:
Implements message padding and closes #251 
Also implements a transport message handling thus closes #61 
Depends on Qabel/qabel-drop#14 to update the maximum drop message size on the drop server.

Support for multiple drop message binary transport formats

---

src/main/java/de/qabel/core/module/ModuleManager.java

Does not prevent multiple `ModuleManagers`s, which are still needed for our tests.
We decided this in the meeting.
See #278 for more info.
If the ticket can be closed, tell me.

Implements a static getter to get the default ModuleManager.

---

src/main/java/de/qabel/core/drop/AdjustableDropIdGenerator.java
src/main/java/de/qabel/core/drop/DropIdGenerator.java
src/main/java/de/qabel/core/drop/DropURL.java
src/test/java/de/qabel/core/drop/DropIdGenerationTest.java

I implemented a modular drop id generation.
* DropIdGenerator is an abstract drop id generator. Defines API.
* AdjustableDropIdGenerator is a simple randomizing drop id generator as proposed in [drop id choosing discussion](https://github.com/Qabel/qabel-doc/issues/16#issuecomment-52052136)
I think the AdjustableDropIdGenerator is a good placeholder until we come up with something better.
Well it's definitely better than the current fixed dummy id.

Modular drop id generation

---

src/main/java/de/qabel/core/drop/DropURL.java

Name of the method shouldn't be misleading any more.
Bug was found by @thechauffer in #281.
Closes #283.

Renamed checkURL() to checkDropIdFromUrl()

---

src/main/java/de/qabel/core/crypto/AbstractBinaryDropMessage.java
src/main/java/de/qabel/core/crypto/BinaryDropMessageV0.java
src/main/java/de/qabel/core/drop/DropController.java
src/main/java/de/qabel/core/exceptions/QblDropInvalidMessageSizeException.java

It is not unlikely that binary drop messages are received that have the wrong
size compared to expectation implied by the header version byte.
This may for instance happen, if someone maliciously uploads invalid messages or
simply due to broken clients.
This patch fixes the handling of this such unexpected sizes.
They are no longer escalated to a RuntimeException (as was a bug), but are now
logged and then skipped.
Therefore, a new exception class is introduced to distinguish this size
mismatches from other critical version mismatches.

Fix erroneous escalation of invalid binary drop messages

---

src/main/java/de/qabel/core/drop/DropController.java
src/main/java/de/qabel/core/http/DropHTTP.java
src/test/java/de/qabel/core/http/DropHTTPTest.java

The DropHTTP returns HTTPResult for ```send```, ```receive``` and ```probe```. So they (especially ```receive```) return more information.

DropHTTP with HTTPResult

---

build.gradle
src/main/java/de/qabel/core/config/ContactsActor.java
src/main/java/de/qabel/core/config/Entity.java
src/main/java/de/qabel/core/config/Persistence.java
src/main/java/de/qabel/core/config/SQLitePersistence.java
src/main/java/de/qabel/core/crypto/CryptoUtils.java
src/test/java/de/qabel/core/config/ContactsActorTest.java
src/test/java/de/qabel/core/config/PersistenceTest.java

This PR is based on #305.
This adds a Persistence class to persist Serializable objects. It probably isn't completely finished, but worth a look. SQLitePersistence uses SQLite as a simple blob storage. 
Entity has a new UUID field which can be used to get or remove a specific persisted object. I introduced this artificial ID, because it is stored unencrypted in the database (to allow lookups). Using actual values like the key id would leak this information.
The serialized data is encrypted with AES256 GCM and a random nonce per object. A master key is used to encrypt all objects. This master key itself is also AES256 GCM encrypted with nonce and a key derived from via PBKDF2 from a password and a random salt. This allows easy password changed by just re-encrypting the master key instead …

Added object persistence

---

src/main/java/de/qabel/core/config/ContactsActor.java

This will fix one of the errors, which showed up in Qabel/qabel#9.
This PR makes the getDefault in ContactsActor public, because otherwise the function is only package-private. It is used by the desktop-module, which fails to build.

Makes the function public

---

src/test/java/de/qabel/core/module/ModuleManagerTest.java

First renames the test, so we will not forget it.
And then ignores the test for now, because it randomly fails.

Ignores lifeCycleTest

---

.travis.yml

Travis will now build the meta repository to test of something besides qabel core got broken.
At the moment the build will fail because of helloworld.
Edit:
https://github.com/Qabel/qabel/pull/9 should be merged before.

configured travis to build the meta repository

---

src/main/java/de/qabel/core/config/EntityMap.java

This adapts the put and remove functions to fit to the signature of Map interface of the very same name. The old functions were misleading and counter-intuitive (put returned false if already was a Entity associated to the same key identifier but replaced it anyway).
The new behaviour is how developers expect a put function to work from the Map interface.
Furthermore, I reduced to scope of the class to package private because a public scope is unnecessary for this abstract helper class.
The need for a clarification of EntityMap API has originally been expressed in https://github.com/Qabel/qabel-core/pull/305#discussion_r29244060
Closes #287

Adapt EntityMap to fit the conventions of the Map interface

---

src/main/java/de/qabel/core/drop/DropActor.java
src/test/java/de/qabel/core/MultiPartCryptoTest.java
src/test/java/de/qabel/core/drop/DropActorTest.java
src/test/java/de/qabel/core/drop/DropCommunicatorUtil.java

The DropserverUrls should not contain the dropIDs, so we have to
check the dropUrls of the identities.
Closes. #182

DropActor uses now the dropUrls of the identities instead of DropServerUrls

---

src/main/java/de/qabel/core/config/ResourceActor.java

Using a  parameterized type here was just a mistake.

Removed unnecessary generic from ResourceActor constructor

---

src/main/java/de/qabel/core/config/Persistence.java
src/main/java/de/qabel/core/config/SQLitePersistence.java
src/main/java/de/qabel/core/exceptions/QblInvalidEncryptionKeyException.java
src/test/java/de/qabel/core/MultiPartCryptoTest.java
src/test/java/de/qabel/core/config/PersistenceTest.java
src/test/java/de/qabel/core/config/ResourceActorTest.java
src/test/java/de/qabel/core/drop/DropActorTest.java

I discovered, that instantiating a persistence with a wrong encryption password isn't handled very well. This adds an exception for this case.
Requires: https://github.com/Qabel/qabel-desktop/pull/24

Added exception when opening persistence with wrong password

---

src/main/java/de/qabel/core/drop/DropMessage.java
src/test/java/de/qabel/core/drop/AcknowledgeIdGenerationTest.java

* The method name had a spelling error
* == instead of equals was used for String comparison

Fix enableAcknowledging in DropMessage

---

src/main/java/de/qabel/core/drop/DropActor.java

Both members were not used anywhere.

Removed unused Gson and GsonBuilder

---

settings.gradle

qable-core can be built without submodules and without needing the whole
meta qabel-repository.
The README.md includes up to date build instructions.

Fix gradle build without meta repo

---

src/main/java/de/qabel/core/exceptions/QblException.java

This allows us to propagate the original cause for the exception.
Resolves #417

Create additional contsructors for QblException

---

src/test/java/de/qabel/core/MultiPartCryptoTest.java
src/test/java/de/qabel/core/drop/DropActorTest.java
src/test/java/de/qabel/core/http/DropHTTPTest.java

The new DropServer does not like port 6000, so we use the flask standard port 5000.
Needed for qabel/qabel-drop#26

Changes the port from 6000 to 5000

---

src/main/java/de/qabel/core/config/Persistence.java
src/main/java/de/qabel/core/config/SQLitePersistence.java
src/test/java/de/qabel/core/config/PersistenceTest.java

Most methods were protected, thus couldn't be accessed from outside, now they are public.
Additionally, `getEntity` and `getEntities` returned instances of Persistence only even though the exact Class (subclass of Persistence) is known. This fixes those signatures to return the correct type.
And both commits should reference Qabel/qabel-desktop#53 , I just mixed up the issue numbers.

fixed interface of Persistence

---

src/main/java/de/qabel/core/drop/DropMessage.java

Required to use this method from qabel-android for receiving DropMessages without the DropActor.

Change visibility of registerSender in DropMessage to public

---

src/main/java/de/qabel/core/crypto/CryptoUtils.java
src/test/java/de/qabel/core/crypto/CryptoUtilsTest.java
src/test/java/de/qabel/core/crypto/DelayedStream.java

Currently, when the same instance of cryptoUtils is used for multiple de- or encryptions, those need to be sequential. Concurrent calls use the same `GCMBlockCipher` instance and at least one of them will fail.
cause for Qabel/qabel-desktop#125

allow concurrent cryption on CryptoUtils

---

src/main/java/de/qabel/core/accounting/AccountingHTTP.java

As the block client needs to send an auth token, we need a way to extract it from the AccountingHttp. This way, the block client can "authorize" it's request without knowing how to communicate with the accounting server itself.
This feature is required for Qabel/qabel-desktop#112
PS: the diff looks pretty bad. Actually I just extracted the `addHeader("Authorization"` stuff to the `authorize(HttpRequest)` method and moved the repeated 
```JAVA
if (server.getAuthToken() == null) {
login();
}
... server.getAuthToken()
```
code to a single `getAuthToken()` call

allow external request authorization with accounting token

---

src/main/java/de/qabel/core/crypto/CryptoUtils.java
src/test/java/de/qabel/core/crypto/CryptoUtilsTest.java
src/test/java/de/qabel/core/crypto/DelayedStream.java

see #451 for details
srsly don't know how to test this as the margin for threading issues is the `hmac.update` itself and the `write` to a local memorybased stream.
+fixed code style issues mentioned by @L-Henke

#451 don't reuse HMac on CryptoUtils to make its usage thread safe, too

---

CHANGELOG.md
Vagrantfile
box/src/main/java/de/qabel/box/storage/AbstractNavigation.java
box/src/main/java/de/qabel/box/storage/BoxObject.java
box/src/main/java/de/qabel/box/storage/DirectoryMetadata.java
box/src/main/java/de/qabel/box/storage/command/CreateFileChange.java
box/src/main/java/de/qabel/box/storage/command/UpdateFileChange.java
box/src/test/java/de/qabel/box/storage/BoxVolumeTest.java
start-servers.sh

the core part of #488.
I'm still searching a way of reusing that code of the `UpdateFileChange`-Command for the sync (one layer above the AbstractNavigation). Unfortunately, the sync code will need the SyncIndex to determine if the "conflict" / "information mismatch" is due to a remote change (real conflict) or a preceding upload (just looks like a conflict like create file => change file)

#488 on filename conflict, the remote file is renamed

---

box/src/main/java/de/qabel/box/storage/AbstractMetadata.kt
box/src/main/java/de/qabel/box/storage/AbstractNavigation.kt
box/src/main/java/de/qabel/box/storage/BoxNavigation.kt
box/src/main/java/de/qabel/box/storage/DefaultIndexNavigation.kt
box/src/main/java/de/qabel/box/storage/LocalReadBackend.java
box/src/main/java/de/qabel/box/storage/jdbc/JdbcDirectoryMetadata.kt
box/src/test/java/de/qabel/box/storage/BoxVolumeTest.java

according to #494 , the empty DM gets inserted to the parent-dm which is instantly uploaded, too, to make sure that if it is required to merge two newly created folders, they don't need to be merged because they latter one is empty.

resolves #494 pessimistic folder commit for conflict prevention

---

box/src/main/java/de/qabel/box/storage/AbstractNavigation.kt
box/src/main/java/de/qabel/box/storage/BoxNavigation.kt
box/src/main/java/de/qabel/box/storage/jdbc/JdbcDirectoryMetadataFactory.kt
core/jni/scalarmult_test.c
core/src/main/java/de/qabel/core/repository/sqlite/SqliteDropStateRepository.kt

The remaining warnings are deprecation warnings, one unused variable that improves readability, and a parameter that will be used in the future:
```
w: /home/mabe/Projekte/_qabel/core/box/src/main/java/de/qabel/box/storage/AbstractNavigation.kt: (44, 35): 'DEFAULT_AUTOCOMMIT_DELAY: Long' is deprecated.
w: /home/mabe/Projekte/_qabel/core/box/src/main/java/de/qabel/box/storage/AbstractNavigation.kt: (172, 54): Parameter 'expectedFile' is never used
w: /home/mabe/Projekte/_qabel/core/box/src/main/java/de/qabel/box/storage/AbstractNavigation.kt: (206, 17): 'updateFileMetadata(BoxFile): Unit' is deprecated. Overrides deprecated member in 'de.qabeavigation'. should only be called internally (on update)
w: /home/mabe/Projekte/_qabel/core/box/src/main/java/de/qabel/box/storage/AbstractNavigation.k …
```

Fix some Kotlin warnings

---

box/src/main/java/de/qabel/box/storage/AbstractNavigation.kt
box/src/main/java/de/qabel/box/storage/Hash.kt
box/src/main/java/de/qabel/box/storage/command/UpdateFileChange.kt
box/src/test/java/de/qabel/box/storage/BoxVolumeTest.java
box/src/test/java/de/qabel/box/storage/command/UpdateFileChangeTest.kt

When a file is updated and the existing file
has the same hash, the update is ignored
and the new block is deleted
Fixes #492

Merge identical files when updating

---

box/src/main/java/de/qabel/box/storage/AbstractNavigation.kt
box/src/main/java/de/qabel/box/storage/command/DirectoryMetadataChange.kt
box/src/main/java/de/qabel/box/storage/command/UpdateFileChange.kt
box/src/test/java/de/qabel/box/storage/command/UpdateFileChangeTest.kt

Fixup for concerns raised in https://github.com/Qabel/qabel-core/pull/568

Delete the block in postprocess

---

box/src/main/java/de/qabel/box/storage/AbstractNavigation.kt
box/src/main/java/de/qabel/box/storage/DefaultIndexNavigation.kt
box/src/test/java/de/qabel/box/storage/BoxVolumeTest.java

Autocommit mitigated most of the problem, but only if
another change like creating a folder happened. Just sharing a
file from the subfolder did not force a commit in the index navigation
Fixes #543

Force commit of index navigation after sharing

---

box/src/main/java/de/qabel/box/storage/jdbc/migration/DMMigration1467796453Init.kt
box/src/test/java/de/qabel/box/storage/jdbc/JdbcDirectoryMetadataTest.kt

The published release doesn't set a user_version, so any existing DMs will be migrated which crashes because the tables already exist.
See https://github.com/Qabel/qabel-android/issues/646

Test for upgrading from old versions

---

box/src/main/java/de/qabel/box/storage/AbstractNavigation.kt
box/src/main/java/de/qabel/box/storage/command/CreateFolderChange.kt
box/src/main/java/de/qabel/box/storage/dto/BoxPath.kt
box/src/test/java/de/qabel/box/storage/AbstractNavigationTest.kt
box/src/test/java/de/qabel/box/storage/BoxVolumeLocalTest.kt
box/src/test/java/de/qabel/box/storage/BoxVolumeTest.kt
box/src/test/java/de/qabel/box/storage/StubReadBackend.kt
box/src/test/java/de/qabel/box/storage/StubWriteBackend.kt
core/src/main/java/de/qabel/core/util/iteratorExtensions.kt
core/src/test/java/de/qabel/core/index/server/IndexHTTPTest.kt

#496 commands publish their boxObject

---

box/src/main/java/de/qabel/box/storage/AbstractMetadata.kt
box/src/main/java/de/qabel/box/storage/jdbc/JdbcDirectoryMetadataFactory.kt
box/src/main/java/de/qabel/box/storage/jdbc/JdbcFileMetadataFactory.kt

Required for https://github.com/Qabel/qabel-android/issues/713 Otherwise the android system tries to load the native jdbc driver which is not available on android 7.

Inject jdbc prefix into factories

---

CHANGELOG.md
core/src/main/java/de/qabel/core/event/EventDispatcher.kt
core/src/main/java/de/qabel/core/event/SubjectEventDispatcher.kt
core/src/test/java/de/qabel/core/event/SubjectEventDispatcherTest.kt

to avoid reoccuring code like
```JAVA
dispatcher
.events()
.filter(e -> e is MessageReceivedEvent)
.map(e -> (MessageReceivedEvent)e)
.nowTheCodeICareAbout()
```
that can now be written as
```JAVA
dispatcher
.events(MessageReceivedEvent.class)
.nowTheCodeICareAbout()
```

casted, filtered event streams

---

box/src/main/java/de/qabel/box/storage/factory/PrefixChooser.kt
box/src/test/java/de/qabel/box/storage/factory/BlockBoxVolumeFactoryTest.kt
core/src/test/java/de/qabel/core/accounting/BoxHttpClientTest.java

The `firstOrNull` usages in combination with the replacements of `firstOrElse` -> `?:` make sure that expensive calls like `hasIndex` are only done until one matching candidate prefix was found (because that's sufficient) and is a huge speedup when we have 50+ prefixes like the testaccount.
More important is the 
```KOTLIN
identity.prefixes.add(prefix)
```
it assures that remote-only-prefixes are added to the local identity and can be used on the next use. Otherwise the client would call choose() on every client start which is especially expensive on the TEQS.

optimized PrefixChooser
