Qabel/qabel-core

src/main/java/de/qabel/core/crypto/CryptoUtils.java
This is for example needed in the storage component which is going
to use the streaming crypto api.
Closes #238
=> Added a publicly accessible generation function for symmetric keys

src/main/java/de/qabel/core/drop/DropController.java, src/test/java/de/qabel/core/drop/DropControllerTest.java
Concatenates the header with the encrypted message and removes it from the received message.
Fixes #242
=> 242 add versionheader to drop message

src/main/java/de/qabel/core/module/ModuleManager.java
=> Let ModuleManager.settings be a single Settings-instance, not a Set of Settings.

src/main/java/de/qabel/core/config/Contact.java, src/main/java/de/qabel/core/crypto/CryptoUtils.java, src/main/java/de/qabel/core/crypto/QblPrimaryKeyPair.java, src/main/java/de/qabel/core/crypto/QblPrimaryPublicKey.java, src/main/java/de/qabel/core/drop/DropController.java, src/test/java/de/qabel/core/MultiPartCryptoTest.java, src/test/java/de/qabel/core/crypto/CryptoUtilsTest.java, src/test/java/de/qabel/core/crypto/QblKeyFactoryTest.java, src/test/java/de/qabel/core/crypto/QblKeySerializationTest.java, src/test/java/de/qabel/core/crypto/QblKeyTest.java, src/test/java/de/qabel/core/drop/DropControllerTest.java
=> Issue #255 Check core of deprecated code 

.travis.yml, build.gradle
Moved the build directories.
Gradle starts the servers now, no need for doing it by hand anymore.
Based on @k-c13 work.
=> Updated gradle and travis config.

.travis.yml, build.gradle
Reverts Qabel/qabel-core#274
Because of missunderstandings in the team, this code will no move to the Qabel meta repo.
=> Revert "Updated gradle and travis config."

src/test/java/de/qabel/core/http/DropHTTPTest.java
to one byte greater than the server accepts.
Closes #276
=> Changed size of drop message size test

src/main/java/de/qabel/core/config/LocalSettings.java, src/main/java/de/qabel/core/config/SyncedSettings.java, src/test/java/de/qabel/core/config/ConfigSerializationTest.java
=> Issue 249 refactoring config classes invocation de serialization

src/test/java/de/qabel/core/http/DropHTTPTest.java
Client side implementation of Qabel/qabel-doc#82
Depends on Qabel/qabel-drop#15
=> Changed http status code 404 to 204

.travis.yml
=> remove irc notifications by travis

CONTRIBUTING.md
=> Code conventions if always with { }

.travis.yml
Unsilence install commands to avoid timout mentioned in #308
=> unsilence install commands

CONTRIBUTING.md
Define how to deal with depended methods calls.
=> Fixes #303

CONTRIBUTING.md
Contains style mentions from #279
Contributes to #287
=> Contributing how to document

src/main/java/de/qabel/core/config/AbstractModuleSettings.java, src/main/java/de/qabel/core/config/Account.java, src/main/java/de/qabel/core/config/Accounts.java, src/main/java/de/qabel/core/config/ConfigActor.java, src/main/java/de/qabel/core/config/DropServer.java, src/main/java/de/qabel/core/config/DropServers.java, src/main/java/de/qabel/core/config/Identities.java, src/main/java/de/qabel/core/config/LocalSettings.java, src/main/java/de/qabel/core/config/LocaleModuleSettings.java, src/main/java/de/qabel/core/config/Settings.java, src/main/java/de/qabel/core/config/StorageServer.java, src/main/java/de/qabel/core/config/StorageServers.java, src/main/java/de/qabel/core/config/StorageVolume.java, src/main/java/de/qabel/core/config/StorageVolumes.java, src/main/java/de/qabel/core/config/SyncedModuleSettings.java, src/test/java/de/qabel/core/config/ConfigActorTest.java, src/test/java/de/qabel/core/config/ConfigHashCodeTest.java
Depends on PR #305.
Closes #298.
=> Issue298 part2 port config component to ackack

src/main/java/de/qabel/core/config/SQLitePersistence.java
All resources are now auto-closed by usage of try with resources.
Edit: An exception while executing a statement could leave the database locked. Now try with resources are ensuring, that the statements and result sets are closed in every case. https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
=> Fixed errors with unclosed resources in SQLitePersistence

.gitmodules
See Qabel/qabel#10
Warning: #328 should be merged before this.
=> Removed submodule ackack

.travis.yml
=> Enhance travis build

src/main/java/de/qabel/core/module/ModuleThread.java
Additional description for #352
=> Added Javadoc to ModuleThread

.travis.yml
Closes #365 
PS: The tests with openjdk7 and oraclejdk8 are allowed to fail.
=> Migrate to travis container and caching

src/main/java/de/qabel/core/config/Persistence.java, src/main/java/de/qabel/core/config/SQLitePersistence.java
The changed visibility is required to allow Persistence implementations outside of the package.
=> Changed visibility of Persistence member and methods

.travis.yml
to speed-up travis CI. From issue Qabel/qabel#16.
closes Qabel/qabel#16
=> travis.yml in qabel-core with git --depth option

.travis.yml, README.md, build.gradle
in this branch because of travis
=> changes for native build of ec lib

build.gradle, src/main/java/de/qabel/core/config/Persistence.java, src/main/java/de/qabel/core/config/SQLitePersistence.java, src/main/java/de/qabel/core/crypto/BinaryDropMessageV0.java, src/main/java/de/qabel/core/crypto/CryptoUtils.java, src/main/java/de/qabel/core/crypto/QblECPublicKey.java, src/main/java/de/qabel/core/crypto/QblEcKeyPairTypeAdapter.java, src/main/java/de/qabel/core/crypto/QblEcPublicKeyTypeAdapter.java, src/main/java/de/qabel/core/drop/DropIdGenerator.java, src/main/java/de/qabel/core/drop/DropURL.java, src/main/java/de/qabel/core/storage/StorageBlob.java, src/test/java/de/qabel/core/crypto/CryptoUtilsTest.java
Removed all bouncycastle dependencies by using spongycastle. The spongycastle API is used directly, not via jce provider. Solves issue #413 .
=> Spongycastle integration

src/main/java/de/qabel/core/accounting/AccountingHTTP.java, src/main/java/de/qabel/core/accounting/AccountingProfile.java, src/test/java/de/qabel/core/accounting/AccountingHTTPTest.java
=> Multiple prefixes in core

src/main/java/de/qabel/core/crypto/CryptoUtils.java, src/test/java/de/qabel/core/crypto/CryptoUtilsTest.java
Recovered false returning when decryption fails. Test to proof the correct response was added. Solves #421
=> Decryption fail response

src/main/java/de/qabel/core/config/Contact.java, src/main/java/de/qabel/core/config/ContactTypeAdapter.java, src/main/java/de/qabel/core/config/Identity.java, src/test/java/de/qabel/core/config/ConfigEqualsTest.java, src/test/java/de/qabel/core/config/ConfigHashCodeTest.java, src/test/java/de/qabel/core/config/ConfigSerializationTest.java
according to Qabel/qabel.github.io#128
=> extended identity and contact by email and phone

src/main/java/de/qabel/core/drop/DropMessageCryptorUtil.java, src/test/java/de/qabel/core/drop/DropMessageCryptorUtilTest.java
=> Added DropMessageCryptorUtil to manually en- and decrypt DropMessages

src/main/java/de/qabel/core/accounting/AccountingHTTP.java, src/test/java/de/qabel/core/accounting/AccountingHTTPTest.java, src/test/java/de/qabel/core/accounting/CloseableHttpClientStub.java, src/test/java/de/qabel/core/accounting/CloseableHttpResponseStub.java
Client implementation of /api/v0/auth/password/reset/
=> implemented resetPassword for AccountingHTTP Qabel/qabel-desktop#55

CONTRIBUTING.md
=> reduced required integrators to 1 for contributions

CONTRIBUTING.md
Added security related contribution guidelines from the [wiki](https://github.com/Qabel/qabel-core/wiki/Secure-Code-Guideline). Solves #21
=> Added security related contributing guidelines

src/main/java/de/qabel/core/config/EncryptedPersistence.java, src/main/java/de/qabel/core/config/Persistence.java, src/main/java/de/qabel/core/config/ResourceActor.java, src/main/java/de/qabel/core/config/SQLiteEncryptedPersistence.java, src/test/java/de/qabel/core/config/EncryptedPersistenceTest.java, src/test/java/de/qabel/core/config/ResourceActorTest.java, src/test/java/de/qabel/core/drop/DropActorTest.java
This allows to either implement an encrypted persistence storage or an
unencrypted persistence storage.
Closes #425
=> Extracted EncryptedPersistence from Persistence

src/main/java/de/qabel/core/config/Identity.java
Added list of prefixes to Identity as discussed with @audax.
=> Added list of prefixes to Identity

src/main/java/de/qabel/core/config/Identity.java, src/test/java/de/qabel/core/config/ConfigHashCodeTest.java
=> Added prefixes to hashCode

src/main/java/de/qabel/core/accounting/AccountingHTTP.java, src/main/java/de/qabel/core/exceptions/QblCreateAccountFailException.java, src/test/java/de/qabel/core/accounting/AccountingHTTPTest.java
add createBoxAccount into AccountingHTTP
delete getCredentials and the corresponding test
=> add createBoxAccount into AccountingHTTP

src/main/java/de/qabel/core/accounting/AccountingHTTP.java, src/main/java/de/qabel/core/accounting/PrefixDto.java, src/main/java/de/qabel/core/accounting/PrefixListDto.java
Qabel/qabel-accounting#43
needed since Qabel/qabel-accounting#45
=> modified AccountingHttp for new prefix resource

src/main/java/de/qabel/core/drop/ProofOfWork.java, src/test/java/de/qabel/core/drop/ProofOfWorkTest.java
This implements the calculation of a proof of work according to the spec in https://github.com/Qabel/qabel.github.io/pull/130
=> PoW calculation

src/main/java/de/qabel/core/http/DropHTTP.java, src/test/java/de/qabel/core/config/IdentityExportImportTest.java
=> Add authorization header to drop http

src/main/java/de/qabel/core/accounting/AccountingHTTP.java, src/main/java/de/qabel/core/accounting/AccountingProfile.java, src/main/java/de/qabel/core/config/AccountingServer.java, src/test/java/de/qabel/core/accounting/AccountingHTTPTest.java, src/test/java/de/qabel/core/accounting/TestAccountingServerBuilder.java, src/test/java/de/qabel/core/http/DropHTTPTest.java
=> fixed AccountingHTTP for features moved to block server

Vagrantfile, src/main/java/de/qabel/core/exceptions/QblCreateAccountFailException.java, src/main/java/de/qabel/core/http/DropHTTP.java, src/main/java/de/qabel/core/http/HTTPResult.java, src/test/java/de/qabel/core/accounting/AccountingHTTPTest.java, src/test/java/de/qabel/core/accounting/TestAccountingServerBuilder.java, src/test/java/de/qabel/core/http/DropHTTPTest.java
fixes #471 
adds a Vagrantfile that can do a full build (including all 3 servers)
depends on https://github.com/Qabel/qabel-drop/pull/44
=> #471 pass last-modified header

core/src/main/java/de/qabel/core/config/Identity.java, core/src/main/java/de/qabel/core/config/IdentityObserver.java, core/src/test/java/de/qabel/core/config/ConfigHashCodeTest.java, core/src/test/java/de/qabel/core/config/IdentityObservableTest.java
#256 added notify observers in the identity
=> Identity 256

core/src/main/java/de/qabel/core/service/MainChatService.kt, core/src/test/java/de/qabel/core/service/ChatServiceTest.kt
=> fix set Etag

core/src/main/java/de/qabel/core/http/DropServerHttp.kt, core/src/main/java/de/qabel/core/http/MainDropServer.kt, core/src/test/java/de/qabel/core/service/ChatServiceTest.kt
Still missing the test because the MainDropServer doesn't have a test…
=> Send "eTag" in the correct header

core/src/main/java/de/qabel/core/repository/sqlite/ClientDatabase.kt, core/src/main/java/de/qabel/core/repository/sqlite/HasVersion.kt, core/src/main/java/de/qabel/core/repository/sqlite/PragmaVersion.kt, core/src/main/java/de/qabel/core/repository/sqlite/PragmaVersionAdapter.kt, core/src/test/java/de/qabel/core/repository/DesktopClientDatabaseTest.java
Extract the logic from PragmaVersionAdapter into a class.
=> Extract pragmaversion logic

core/src/main/java/de/qabel/core/drop/DropSerializer.kt
=> Include acknowledge id in drop message

core/src/main/java/de/qabel/core/config/IdentityExportImport.java, core/src/test/java/de/qabel/core/config/IdentityExportImportTest.java
=> Do not export/import identity database id

box/src/main/java/de/qabel/box/storage/BoxVolumeImpl.kt, box/src/test/java/de/qabel/box/storage/BoxVolumeBlockTest.java, box/src/test/java/de/qabel/box/storage/BoxVolumeLocalTest.java, box/src/test/java/de/qabel/box/storage/BoxVolumeTest.java
Fixes #578 
Fixes https://github.com/Qabel/qabel-android/issues/628
=> Fix root ref in volume

core/src/main/java/de/qabel/core/repository/ContactRepository.kt, core/src/main/java/de/qabel/core/repository/sqlite/SqliteContactRepository.kt, core/src/test/java/de/qabel/core/repository/SqliteContactRepositoryTest.kt, core/src/test/java/de/qabel/core/repository/inmemory/InMemoryContactRepository.kt
resolves #580 
Add real delete-method to interface
=> update contact repo

core/src/test/java/de/qabel/core/extensions/testExtensions.kt, core/src/test/java/de/qabel/core/repository/SqliteContactRepositoryTest.kt
=> assertThrows for expected exceptions

chat/src/main/java/de/qabel/chat/service/MainSharingService.kt, chat/src/main/java/de/qabel/chat/service/SharingService.kt, chat/src/test/java/de/qabel/chat/service/ChatServiceTest.kt, chat/src/test/java/de/qabel/chat/service/SharingServiceTest.kt, core/src/test/java/de/qabel/core/extensions/testExtensions.kt
some extra tests for chatservice
=> Chatservice tests

core/src/main/java/de/qabel/core/index/EndpointBase.kt, core/src/main/java/de/qabel/core/index/IndexHTTP.kt, core/src/main/java/de/qabel/core/index/IndexServer.kt, core/src/main/java/de/qabel/core/index/VerificationCodeEndpoint.kt, core/src/main/java/de/qabel/core/index/VerificationCodeEndpointImpl.kt, core/src/main/java/de/qabel/core/index/errors.kt, core/src/test/java/de/qabel/core/index/IndexHTTPTest.kt, core/src/test/java/de/qabel/core/index/VerificationCodeEndpointTest.kt
Fixes #590
Tiny bit untested, but should work.
=> IndexServer.confirmVerificationCode, .denyVerificationCode

core/src/main/java/de/qabel/core/index/MainIndexService.kt
resolves automerge fail -> remove logging extension imports
=> Fix automerge

core/src/main/java/de/qabel/core/repository/sqlite/SqliteContactRepository.kt, core/src/main/java/de/qabel/core/repository/sqlite/migration/Migration1460997044IndexIdentity.java
changed notifyObservers when deleting contact and version migration
=> Submenu contact 387

box/src/main/java/de/qabel/box/storage/AbstractNavigation.kt
=> Reuse thread pool in AbstractNavigation

core/src/main/java/de/qabel/core/config/Identity.java, core/src/main/java/de/qabel/core/repository/sqlite/DesktopClientDatabase.kt, core/src/main/java/de/qabel/core/repository/sqlite/hydrator/IdentityAdapter.kt, core/src/main/java/de/qabel/core/repository/sqlite/migration/Migration1460997045UploadableIdentity.java, core/src/main/java/de/qabel/core/repository/sqlite/schemas/IdentityDB.kt, core/src/test/java/de/qabel/core/config/ConfigHashCodeTest.java, core/src/test/java/de/qabel/core/repository/SqliteIdentityRepositoryTest.kt
Allows to disable index upload for an identity
=> uploadEnabled Flag for private Identities

box/src/main/java/de/qabel/box/storage/jdbc/JdbcFileMetadataFactory.kt, box/src/main/java/de/qabel/box/storage/jdbc/migration/FMMigration1468173861Init.kt, chat/src/main/java/de/qabel/chat/service/MainChatService.kt, chat/src/main/java/de/qabel/chat/service/MainSharingService.kt, chat/src/test/java/de/qabel/chat/service/ChatServiceTest.kt, chat/src/test/java/de/qabel/chat/service/SharingServiceTest.kt
Resolves issues for android integration
fixes #608
=> Fix sharing

core/src/main/java/de/qabel/core/repository/sqlite/hydrator/ContactAdapter.kt, core/src/main/java/de/qabel/core/repository/sqlite/hydrator/IdentityAdapter.kt, core/src/test/java/de/qabel/core/repository/SqliteContactRepositoryTest.kt, core/src/test/java/de/qabel/core/repository/SqliteIdentityRepositoryTest.kt
=> remove nullable email, phone

core/src/main/java/de/qabel/core/repository/sqlite/SqliteIdentityRepository.kt, core/src/test/java/de/qabel/core/repository/SqliteIdentityRepositoryTest.kt
=> fix save identity with existing contact

core/src/main/java/de/qabel/core/repository/ContactRepository.kt, core/src/main/java/de/qabel/core/repository/sqlite/SqliteIdentityRepository.kt, core/src/test/java/de/qabel/core/repository/SqliteIdentityRepositoryTest.kt, core/src/test/java/de/qabel/core/repository/inmemory/InMemoryContactRepository.kt, core/src/test/java/de/qabel/core/repository/inmemory/InMemoryIdentityRepository.kt
=>  don't delete identities contacts associations on update

box/src/main/java/de/qabel/box/http/HttpWriteBackend.kt, core/src/main/java/de/qabel/core/accounting/BoxClient.java, core/src/main/java/de/qabel/core/accounting/DummyRequestAuthorizer.kt, core/src/main/java/de/qabel/core/accounting/RequestAuthorizer.kt, core/src/main/java/de/qabel/core/accounting/SimpleRequestAuthorizer.kt
stub and simple and the BoxClient is also a RequestAuthorizer
=> RequestAuthorizer for IndexHttp

core/src/main/java/de/qabel/core/ui/EntityUIExtensions.kt, core/src/test/java/de/qabel/core/ui/EntityUIExtensionTest.kt
=> filter initials for letters and digits

CHANGELOG.md, box/src/test/java/de/qabel/box/http/HttpWriteBackendTest.kt, box/src/test/java/de/qabel/box/storage/BoxVolumeBlockTest.kt, box/src/test/java/de/qabel/box/storage/factory/BlockBoxVolumeFactoryTest.kt, box/src/test/java/de/qabel/box/storage/jdbc/JdbcDirectoryMetadataTest.kt, chat/src/test/java/de/qabel/chat/repository/SqliteChatDropMessageRepositoryTest.kt, core/src/test/java/de/qabel/core/TestServer.kt, core/src/test/java/de/qabel/core/TestUtil.kt, core/src/test/java/de/qabel/core/accounting/TestAccountingServerBuilder.java, core/src/test/java/de/qabel/core/config/EntityTest.kt, core/src/test/java/de/qabel/core/http/DropHTTPTest.java, core/src/test/java/de/qabel/core/http/MainDropServerTest.kt, core/src/test/java/de/qabel/core/index/server/IndexHTTPTest.kt, core/src/test/java/de/qabel/core/index/server/SearchEndpointTest.kt, core/src/test/java/de/qabel/core/index/server/ServerPublicKeyEndpointTest.kt, core/src/test/java/de/qabel/core/index/server/UpdateEndpointTest.kt, core/src/test/java/de/qabel/core/index/server/VerificationCodeEndpointTest.kt, core/src/test/java/de/qabel/core/repository/EntityManagerTest.java, core/src/test/java/de/qabel/core/repository/SqliteContactRepositoryTest.kt, core/src/test/java/de/qabel/core/repository/SqliteDropUrlRepositoryTest.kt, core/src/test/java/de/qabel/core/repository/SqliteIdentityRepositoryTest.kt
=> #640 configurable test servers

client/build.gradle, settings.gradle
=> client module
